#(define microlily-dir (lyp:this-dir))

"athenian"    = \pincludeOnce #(lyp:join-path microlily-dir "athenian.ly")
"he"          = \pincludeOnce #(lyp:join-path microlily-dir "he.ly")
"ji12"        = \pincludeOnce #(lyp:join-path microlily-dir "ji12.ly")
"promethean"  = \pincludeOnce #(lyp:join-path microlily-dir "promethean.ly")
"regular"     = \pincludeOnce #(lyp:join-path microlily-dir "regular.ly")
"sag60"       = \pincludeOnce #(lyp:join-path microlily-dir "sag60.ly")
"sag72"       = \pincludeOnce #(lyp:join-path microlily-dir "sag72.ly")
"saget"       = \pincludeOnce #(lyp:join-path microlily-dir "saget.ly")
"sagji"       = \pincludeOnce #(lyp:join-path microlily-dir "sagji.ly")
"sagji60"     = \pincludeOnce #(lyp:join-path microlily-dir "sagji60.ly")
"sagji72"     = \pincludeOnce #(lyp:join-path microlily-dir "sagji72.ly")
"sagji224"    = \pincludeOnce #(lyp:join-path microlily-dir "sagji224.ly")
"trojan"      = \pincludeOnce #(lyp:join-path microlily-dir "trojan.ly")
"trojan60"    = \pincludeOnce #(lyp:join-path microlily-dir "trojan60.ly")
"trojan72"    = \pincludeOnce #(lyp:join-path microlily-dir "trojan72.ly")
